/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseResponse;
import io.swagger.client.model.Lang;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LangsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-20T11:03:43.164-07:00")
public class LangsResponse {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("langs")
  private List<Lang> langs = null;

  public LangsResponse code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public LangsResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public LangsResponse langs(List<Lang> langs) {
    this.langs = langs;
    return this;
  }

  public LangsResponse addLangsItem(Lang langsItem) {
    if (this.langs == null) {
      this.langs = new ArrayList<Lang>();
    }
    this.langs.add(langsItem);
    return this;
  }

   /**
   * Get langs
   * @return langs
  **/
  @ApiModelProperty(value = "")
  public List<Lang> getLangs() {
    return langs;
  }

  public void setLangs(List<Lang> langs) {
    this.langs = langs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LangsResponse langsResponse = (LangsResponse) o;
    return Objects.equals(this.code, langsResponse.code) &&
        Objects.equals(this.message, langsResponse.message) &&
        Objects.equals(this.langs, langsResponse.langs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, langs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LangsResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    langs: ").append(toIndentedString(langs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

