/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * NLPDocumentResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-27T16:02:30.755+03:00")
public class NLPDocumentResponse {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("NLPData")
  private List<NLPData> NLPData = null;

  public NLPDocumentResponse code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public NLPDocumentResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public NLPDocumentResponse nlpData(List<NLPData> NLPData) {
    this.NLPData = NLPData;
    return this;
  }

  public NLPDocumentResponse addNlpDataItem(NLPData NLPDataItem) {
    if (this.NLPData == null) {
      this.NLPData = new ArrayList<NLPData>();
    }
    this.NLPData.add(NLPDataItem);
    return this;
  }

   /**
   * Get NLPData
   * @return NLPData
  **/
  @ApiModelProperty(value = "")
  public List<NLPData> getNLPData() {
    return NLPData;
  }

  public void setNLPData(List<NLPData> NLPData) {
    this.NLPData = NLPData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NLPDocumentResponse nlPDocumentResponse = (NLPDocumentResponse) o;
    return Objects.equals(this.code, nlPDocumentResponse.code) &&
        Objects.equals(this.message, nlPDocumentResponse.message) &&
        Objects.equals(this.NLPData, nlPDocumentResponse.NLPData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, NLPData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NLPDocumentResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    NLPData: ").append(toIndentedString(NLPData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

