/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseResponse;
import io.swagger.client.model.TranscriptData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TextDocumentResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-16T10:51:26.266-07:00")
public class TextDocumentResponse {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("transcriptData")
  private List<TranscriptData> transcriptData = null;

  public TextDocumentResponse code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public TextDocumentResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public TextDocumentResponse transcriptData(List<TranscriptData> transcriptData) {
    this.transcriptData = transcriptData;
    return this;
  }

  public TextDocumentResponse addTranscriptDataItem(TranscriptData transcriptDataItem) {
    if (this.transcriptData == null) {
      this.transcriptData = new ArrayList<TranscriptData>();
    }
    this.transcriptData.add(transcriptDataItem);
    return this;
  }

   /**
   * Get transcriptData
   * @return transcriptData
  **/
  @ApiModelProperty(value = "")
  public List<TranscriptData> getTranscriptData() {
    return transcriptData;
  }

  public void setTranscriptData(List<TranscriptData> transcriptData) {
    this.transcriptData = transcriptData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextDocumentResponse textDocumentResponse = (TextDocumentResponse) o;
    return Objects.equals(this.code, textDocumentResponse.code) &&
        Objects.equals(this.message, textDocumentResponse.message) &&
        Objects.equals(this.transcriptData, textDocumentResponse.transcriptData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, transcriptData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextDocumentResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    transcriptData: ").append(toIndentedString(transcriptData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

