/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.GeometryCollection;
import io.swagger.client.model.Point;
import io.swagger.client.model.Point2D;
import org.junit.Assert;
import org.junit.Test;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

/**
 * API tests for GeometryImportApi
 */
public class GeometryImportApiTest extends BaseTest {

    private final GeometryImportApi api = new GeometryImportApi();

    /**
     * Batch import geometry into placeNext
     *
     * Import geometry endpoint allow developer to ingest the batch geometry into placeNext at once. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsGeometryImportPostTest() throws ApiException {
        setup(api.getApiClient());

        GeometryCollection body = new GeometryCollection();
        Point2D point2D = new Point2D();
        point2D.add(BigDecimal.valueOf(139.69244633));
        point2D.add(BigDecimal.valueOf(35.6913648));
        Point point = new Point();
        point.setCoordinates(point2D);
        body.addGeometriesItem(point);
        body.setGeometries(Arrays.asList(point));
        ApiResponse<List<String>> response = api.insightsGeometryImportPostWithHttpInfo(body);

        System.err.println(response);
        //response.getMessage();
        Assert.assertEquals("get 200", 200, response.getStatusCode());

    }


}
