/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BooleanResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HasNLPResultsApi
 */
@Ignore
public class HasNLPResultsApiTest extends BaseTest {

    private final HasNLPResultsApi api = new HasNLPResultsApi();

    
    /**
     * Determines if we have NLP results for a supplied audio file
     *
     * Determines if we have NLP results for a supplied audio file 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsHasNLPResultsAudioIdGetTest() throws ApiException {
        setup(api.getApiClient());
        String audioId = null;
        BooleanResponse response = api.insightsHasNLPResultsAudioIdGet(audioId);

        // TODO: test validations
    }
    
}
