/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.CategoryResponse;
import org.junit.Assert;
import org.junit.Test;

/**
 * API tests for InsightsCategoriesApi
 */
public class InsightsCategoriesApiTest extends BaseTest {

    private final InsightsCategoriesApi api = new InsightsCategoriesApi();

    /**
     * Retrieve NSS Categories Summary
     *
     * Retrieve NSS Categories Summary 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsCategoriesGetTest() throws ApiException {
        setup(api.getApiClient());
        String audioId = null;
        Long start = null;
        Long end = null;
        ApiResponse<CategoryResponse> res = api.insightsCategoriesGetWithHttpInfo(audioId, start, end);
        Assert.assertEquals("status", 200, res.getStatusCode());
        // TODO: test validations
    }
    
}
