/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BaseResponse;
import java.math.BigDecimal;
import java.io.File;
import io.swagger.client.model.UploadAudioResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadAudioApi
 */
@Ignore
public class UploadAudioApiTest extends BaseTest {

    private final UploadAudioApi api = new UploadAudioApi();

    
    /**
     * Uploads audio file for analysis
     *
     * Uploads audio file for analysis 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsUploadAudioPostTest() throws ApiException {
        setup(api.getApiClient());
        File uploadFile = null;
        String deviceLanguage = null;
        Float confidence = null;
        String merge = null;
        String deviceLocation = null;
        BigDecimal sampleRate = null;
        UploadAudioResponse response = api.insightsUploadAudioPost(uploadFile, deviceLanguage, confidence, merge, deviceLocation, sampleRate);

        // TODO: test validations
    }
    
}
