/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.TranscriptResponse;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadTranscriptApi
 */
@Ignore
public class UploadTranscriptApiTest extends BaseTest {

    private final UploadTranscriptApi api = new UploadTranscriptApi();
    
    /**
     * Upload transcripts to Natural Voice
     *
     * Developers use the Upload Transcript API to upload transcripts to Natural Voice for automated text analysis by natural language processing (NLP). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsUploadTranscriptPostTest() throws ApiException {
        setup(api.getApiClient());
        String transcript = null;
        String deviceLanguage = null;
        TranscriptResponse res = api.insightsUploadTranscriptPost(transcript, deviceLanguage);

        Assert.assertEquals("status", 200, res.getCode().intValue());
    }
    
}
